const std = @import("std");

/// Sentinel replaced at render time with a JSON-encoded string literal holding
/// the absolute path to the agit binary.
const binary_token = "__AGIT_BINARY__";

/// Static body of the generated Copilot extension. Copilot auto-discovers
/// `extension.mjs` entrypoints under `~/.copilot/extensions/*/`.
///
/// The extension listens to the public Copilot extension hooks and shells out
/// to `agit copilot-hook` with the same normalized JSON payload shape used by
/// the existing Zig adapter. This keeps the recorder pipeline unchanged while
/// avoiding reliance on Copilot's older hook-config contract.
const body =
    \\// Generated by `agit init`. Records Copilot CLI sessions into the local .agit store.
    \\// Safe to delete; recreate with `agit init --agent copilot`.
    \\import { joinSession } from "@github/copilot-sdk/extension";
    \\import { spawnSync } from "node:child_process";
    \\
    \\const AGIT_BINARY = __AGIT_BINARY__;
    \\const MAX_FIELD = 1000000;
    \\
    \\function replacer(_key, value) {
    \\  if (typeof value === "bigint") return value.toString();
    \\  return value;
    \\}
    \\
    \\function truncate(text) {
    \\  if (typeof text !== "string") return text;
    \\  return text.length > MAX_FIELD ? text.slice(0, MAX_FIELD) : text;
    \\}
    \\
    \\function safeText(value) {
    \\  if (typeof value === "string") return truncate(value);
    \\  if (value === undefined || value === null) return "";
    \\  try {
    \\    return truncate(JSON.stringify(value, replacer));
    \\  } catch {
    \\    return "";
    \\  }
    \\}
    \\
    \\function send(payload) {
    \\  try {
    \\    const json = JSON.stringify(payload, replacer);
    \\    spawnSync(AGIT_BINARY, ["copilot-hook"], {
    \\      input: json,
    \\      timeout: 5000,
    \\      stdio: ["pipe", "ignore", "ignore"],
    \\    });
    \\  } catch {
    \\    // fail-open: never disrupt Copilot
    \\  }
    \\}
    \\
    \\function currentTurnId(turnSeq) {
    \\  return `agturn:copilot-${turnSeq}`;
    \\}
    \\
    \\function currentToolId(turnSeq, toolSeq) {
    \\  return `agtool:copilot-${turnSeq}-${toolSeq}`;
    \\}
    \\
    \\function toolResultText(toolResult) {
    \\  if (!toolResult || typeof toolResult !== "object") return "";
    \\  if (typeof toolResult.sessionLog === "string" && toolResult.sessionLog.length > 0) {
    \\    return truncate(toolResult.sessionLog);
    \\  }
    \\  if (typeof toolResult.textResultForLlm === "string" && toolResult.textResultForLlm.length > 0) {
    \\    return truncate(toolResult.textResultForLlm);
    \\  }
    \\  if (typeof toolResult.error === "string" && toolResult.error.length > 0) {
    \\    return truncate(toolResult.error);
    \\  }
    \\  return safeText(toolResult);
    \\}
    \\
    \\let turnSeq = 0;
    \\let toolSeq = 0;
    \\
    \\await joinSession({
    \\  hooks: {
    \\    onUserPromptSubmitted: async (input) => {
    \\      turnSeq += 1;
    \\      toolSeq = 0;
    \\      send({
    \\        session_id: input.sessionId,
    \\        cwd: input.cwd || process.cwd(),
    \\        turn_id: currentTurnId(turnSeq),
    \\        hook_event_name: "UserPromptSubmit",
    \\        prompt: truncate(input.prompt),
    \\      });
    \\    },
    \\    onPostToolUse: async (input) => {
    \\      if (turnSeq === 0) {
    \\        turnSeq = 1;
    \\      }
    \\      toolSeq += 1;
    \\      send({
    \\        session_id: input.sessionId,
    \\        cwd: input.cwd || process.cwd(),
    \\        turn_id: currentTurnId(turnSeq),
    \\        hook_event_name: "PostToolUse",
    \\        tool_use_id: currentToolId(turnSeq, toolSeq),
    \\        tool_name: input.toolName,
    \\        tool_input: input.toolArgs ?? {},
    \\        tool_result: {
    \\          text_result_for_llm: toolResultText(input.toolResult),
    \\        },
    \\      });
    \\    },
    \\    onAgentStop: async (input) => {
    \\      if (turnSeq === 0) {
    \\        turnSeq = 1;
    \\      }
    \\      send({
    \\        session_id: input.sessionId,
    \\        cwd: input.cwd || process.cwd(),
    \\        turn_id: currentTurnId(turnSeq),
    \\        hook_event_name: "Stop",
    \\        transcript_path: input.transcriptPath,
    \\        stop_reason: input.stopReason,
    \\      });
    \\    },
    \\  },
    \\});
    \\
;

/// Render the extension source with the agit binary path embedded as a JSON
/// string literal. All allocations use `aa`.
pub fn render(aa: std.mem.Allocator, exe: []const u8) ![]const u8 {
    const quoted = try std.json.Stringify.valueAlloc(aa, std.json.Value{ .string = exe }, .{});
    const size = std.mem.replacementSize(u8, body, binary_token, quoted);
    const out = try aa.alloc(u8, size);
    _ = std.mem.replace(u8, body, binary_token, quoted, out);
    return out;
}

test "render embeds the agit binary as a JSON literal" {
    const gpa = std.testing.allocator;
    var arena = std.heap.ArenaAllocator.init(gpa);
    defer arena.deinit();
    const aa = arena.allocator();

    const out = try render(aa, "/home/user/.local/bin/agit");
    try std.testing.expect(std.mem.indexOf(u8, out, "const AGIT_BINARY = \"/home/user/.local/bin/agit\";") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, binary_token) == null);
    try std.testing.expect(std.mem.indexOf(u8, out, "\"copilot-hook\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "onUserPromptSubmitted") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "onPostToolUse") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "onAgentStop") != null);
}

test "render escapes embedded quotes in the binary path" {
    const gpa = std.testing.allocator;
    var arena = std.heap.ArenaAllocator.init(gpa);
    defer arena.deinit();
    const aa = arena.allocator();

    const out = try render(aa, "/weird/pa\"th/agit");
    try std.testing.expect(std.mem.indexOf(u8, out, "/weird/pa\\\"th/agit") != null);
}
