const std = @import("std");

/// Sentinel replaced at render time with a JSON-encoded string literal holding
/// the absolute path to the agit binary.
const binary_token = "__AGIT_BINARY__";

/// Static body of the generated Pi extension. Pi auto-discovers any `*.js`/`*.ts`
/// file dropped into `~/.pi/agent/extensions/` and loads its default export.
///
/// The extension subscribes to Pi lifecycle events and shells out to
/// `agit pi-hook` with a normalized JSON payload on stdin. It is deliberately
/// fail-open: any error spawning agit is swallowed so recording never disrupts
/// Pi. A per-agent-loop `turn_id` is generated so agit can group each prompt,
/// its tool calls, and the final assistant message into one step even when Pi
/// runs multiple internal turns.
const body =
    \\// Generated by `agit init`. Records Pi sessions into the local .agit store.
    \\// Safe to delete; recreate with `agit init --agent pi`.
    \\import { spawnSync } from "node:child_process";
    \\
    \\const AGIT_BINARY = __AGIT_BINARY__;
    \\const MAX_FIELD = 1000000;
    \\
    \\function replacer(_key, value) {
    \\  if (typeof value === "bigint") return value.toString();
    \\  return value;
    \\}
    \\
    \\function truncate(text) {
    \\  if (typeof text !== "string") return text;
    \\  return text.length > MAX_FIELD ? text.slice(0, MAX_FIELD) : text;
    \\}
    \\
    \\function safeText(value) {
    \\  if (typeof value === "string") return truncate(value);
    \\  if (value === undefined || value === null) return "";
    \\  try {
    \\    return truncate(JSON.stringify(value, replacer));
    \\  } catch {
    \\    return "";
    \\  }
    \\}
    \\
    \\function send(payload) {
    \\  try {
    \\    const json = JSON.stringify(payload, replacer);
    \\    spawnSync(AGIT_BINARY, ["pi-hook"], {
    \\      input: json,
    \\      timeout: 5000,
    \\      stdio: ["pipe", "ignore", "ignore"],
    \\    });
    \\  } catch {
    \\    // fail-open: never disrupt Pi
    \\  }
    \\}
    \\
    \\function assistantText(messages) {
    \\  if (!Array.isArray(messages)) return "";
    \\  for (let i = messages.length - 1; i >= 0; i--) {
    \\    const message = messages[i];
    \\    if (!message || message.role !== "assistant") continue;
    \\    const content = message.content;
    \\    if (typeof content === "string") return truncate(content);
    \\    if (Array.isArray(content)) {
    \\      const parts = [];
    \\      for (const block of content) {
    \\        if (block && block.type === "text" && typeof block.text === "string") {
    \\          parts.push(block.text);
    \\        }
    \\      }
    \\      if (parts.length) return truncate(parts.join(""));
    \\    }
    \\    if (typeof message.errorMessage === "string") return truncate(message.errorMessage);
    \\    return "";
    \\  }
    \\  return "";
    \\}
    \\
    \\function context(ctx) {
    \\  let sessionId = "";
    \\  try {
    \\    sessionId = ctx.sessionManager.getSessionId();
    \\  } catch {
    \\    sessionId = "";
    \\  }
    \\  return { session_id: sessionId, cwd: ctx.cwd || process.cwd() };
    \\}
    \\
    \\export default function agitRecorder(pi) {
    \\  let turnSeq = 0;
    \\  let turnId = null;
    \\  const toolArgs = new Map();
    \\
    \\  pi.on("before_agent_start", (event, ctx) => {
    \\    turnSeq += 1;
    \\    turnId = `agturn:pi-${turnSeq}`;
    \\    toolArgs.clear();
    \\    send({
    \\      ...context(ctx),
    \\      hook_event_name: "input",
    \\      turn_id: turnId,
    \\      prompt: safeText(event.prompt),
    \\    });
    \\  });
    \\
    \\  pi.on("tool_execution_start", (event) => {
    \\    toolArgs.set(event.toolCallId, event.args);
    \\  });
    \\
    \\  pi.on("tool_execution_end", (event, ctx) => {
    \\    const args = toolArgs.get(event.toolCallId);
    \\    toolArgs.delete(event.toolCallId);
    \\    send({
    \\      ...context(ctx),
    \\      hook_event_name: "tool_execution_end",
    \\      turn_id: turnId,
    \\      tool_use_id: event.toolCallId,
    \\      tool_name: event.toolName,
    \\      tool_input: args === undefined ? {} : args,
    \\      tool_response: safeText(event.result),
    \\    });
    \\  });
    \\
    \\  pi.on("agent_end", (event, ctx) => {
    \\    send({
    \\      ...context(ctx),
    \\      hook_event_name: "agent_end",
    \\      turn_id: turnId,
    \\      response: assistantText(event.messages),
    \\    });
    \\    turnId = null;
    \\    toolArgs.clear();
    \\  });
    \\}
    \\
;

/// Render the extension source with the agit binary path embedded as a JSON
/// string literal. All allocations use `aa`.
pub fn render(aa: std.mem.Allocator, exe: []const u8) ![]const u8 {
    const quoted = try std.json.Stringify.valueAlloc(aa, std.json.Value{ .string = exe }, .{});
    const size = std.mem.replacementSize(u8, body, binary_token, quoted);
    const out = try aa.alloc(u8, size);
    _ = std.mem.replace(u8, body, binary_token, quoted, out);
    return out;
}

test "render embeds the agit binary as a JSON literal" {
    const gpa = std.testing.allocator;
    var arena = std.heap.ArenaAllocator.init(gpa);
    defer arena.deinit();
    const aa = arena.allocator();

    const out = try render(aa, "/home/user/.local/bin/agit");
    try std.testing.expect(std.mem.indexOf(u8, out, "const AGIT_BINARY = \"/home/user/.local/bin/agit\";") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, binary_token) == null);
    try std.testing.expect(std.mem.indexOf(u8, out, "pi.on(\"before_agent_start\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, out, "\"pi-hook\"") != null);
}

test "render escapes embedded quotes in the binary path" {
    const gpa = std.testing.allocator;
    var arena = std.heap.ArenaAllocator.init(gpa);
    defer arena.deinit();
    const aa = arena.allocator();

    const out = try render(aa, "/weird/pa\"th/agit");
    try std.testing.expect(std.mem.indexOf(u8, out, "/weird/pa\\\"th/agit") != null);
}
